# Numpy Basic Docs

### Import Package to use

In [2]:
import numpy as np

### Numpy version

In [2]:
np.__version__

'1.19.5'

## Array in numpy

In [3]:
arr = np.array([12,32,4234,4543])
print(arr)
type(arr)

[  12   32 4234 4543]


numpy.ndarray

### n-dimensional array

In [4]:
a = np.array([12,32,24,665], ndmin=4) #4 dimensional array
print(a)
print("Dimension",a.ndim) #.ndim is used to see dimension of array

arr_3 = np.array([[[12,32], [212,54]]])
print("Dimension of arr_3 is ", arr_3.ndim)

[[[[ 12  32  24 665]]]]
Dimension 4
Dimension of arr_3 is  3


## Indexing and slicing of nparray

In [5]:
# Array indexing and slicing is same as in python arrays
print(arr)
print("Indexing")
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print("The sum is :", arr[0] + arr[1])

print("\nSlicing")
print(arr[:])
print(arr[0:2])
print(arr[0:])
print(arr[:4])
print(arr[::-1])
print(arr[::2])

[  12   32 4234 4543]
Indexing
12
32
4234
4543
The sum is : 44

Slicing
[  12   32 4234 4543]
[12 32]
[  12   32 4234 4543]
[  12   32 4234 4543]
[4543 4234   32   12]
[  12 4234]


In [6]:
arr = np.arange(20)**2
print(arr[0:10:2])
arr[0:20:2] = 120
for i in arr:
    print(i)

[ 0  4 16 36 64]
120
1
120
9
120
25
120
49
120
81
120
121
120
169
120
225
120
289
120
361


In [7]:
# Multi dimensional array slicing
arr = np.array([[1,2,3],[4,5,6],[9,7,6]])
print("Col " ,arr[:, 1]) #column index 1
print("Row",arr[1, :]) #row 1
print("Row",arr[-1]) #row last equivalent to "arr[1, :]"

Col  [2 5 7]
Row [4 5 6]
Row [9 7 6]


In [8]:
# 3 dimensional array
arr = np.array([[[1,2,3],[2,4,5]],[[3,4,5],[6,8,7]]])
for i in arr:
    print(i)
print("\n\n")
for i in arr.flat: #Iterate over all elements of array
    print(i)

[[1 2 3]
 [2 4 5]]
[[3 4 5]
 [6 8 7]]



1
2
3
2
4
5
3
4
5
6
8
7


## More on ndarray

In [9]:
foo = np.array([12,33,54,556,73,29]) #one dimensional array
print("one dimensional array")
print(foo.shape)
print(foo.ndim)
print(foo.size) 
print(type(foo))
print(foo.dtype)
print(foo.dtype.type) #Type of array
print(foo.dtype.name)
print(foo.itemsize) #Data tyooe size of array
print(foo.data)


# Two dimensional array
print("\nTwo dimensional array")
foo2 = np.array([[12,32],[121,322],[123,54]])
print(foo2.shape)
print(foo2.ndim)
print(foo2.size) 
print(type(foo2))
print(foo2.dtype)
print(foo2.dtype.type) #Type of array
print(foo2.itemsize) #Data tyooe size of array
print(foo2.data)

one dimensional array
(6,)
1
6
<class 'numpy.ndarray'>
int32
<class 'numpy.int32'>
int32
4

Two dimensional array
(3, 2)
2
6
<class 'numpy.ndarray'>
int32
<class 'numpy.int32'>
4


## Creation of ndarray

In [10]:
arr = np.array([1,2,3,4,5], dtype=float) #Dtype defines the type of array
arr.dtype #Datatype of an array
arr 

array([1., 2., 3., 4., 5.])

In [11]:
# Zeros array 
arr = np.zeros(5) #Creates array with given shape and initializes elaments with float 0
arr = np.zeros((2,2)) #Two dimensional array
arr = np.zeros((2,2,5)) #Three dimensional arr

# Ones array
arr = np.ones(5) #Creates array with given shape and initializes elaments with float 1
arr = np.ones((2,2)) #Two dimensional array
arr = np.ones((2,2,5)) #Three dimensional arr

# Empty arrays
arr = np.empty(5) #Creates array with given shape and initializes elaments with garbage value
arr = np.empty((2,2)) #Two dimensional array
arr = np.empty((2,2,5)) #Three dimensional arr

# Printing arr
arr

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [35]:
arr = np.eye(4,5) #returns array with diagonal element = 1
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [12]:
# Arange- creating array  (analogus to range of python)
arr = np.arange(20) #creates array 0 to 20
arr = np.arange(2, 100, 2) #arange(start, stop, step)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [13]:
# Linspace array
arr = np.linspace(1,2,20) #linspace(start , end, how many points between start and end)
arr

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

## Priniting array

In [14]:
arr = np.arange(20).reshape(4,5)
arr
arr>10

# Resizing array
a = np.array([[1,2,3],[4,5,6]])
a.size
a.resize((6,5))
print(a)
a.size

[[1 2 3 4 5]
 [6 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


30

## Operations in array

In [15]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([3,4,5,6,7,8,9,])
c=a+b
b = b**2
print(c>3)
print(a.sum())
print(a.min())
print(a.max())

[ True  True  True  True  True  True  True]
28
1
7


In [16]:
random_instance = np.random.default_rng(1)
a = random_instance.random((3,4))
a+=3
a

array([[3.51182162, 3.9504637 , 3.14415961, 3.94864945],
       [3.31183145, 3.42332645, 3.82770259, 3.40919914],
       [3.54959369, 3.02755911, 3.75351311, 3.53814331]])

In [17]:
#matrix operations
a = np.array([[1,2],[4,3]])
b = np.array([[1,0], [3,5]])
a*b #element wise product
a@b  #Matrix product or dot product
a.dot(b)  #Matrix product or dot product

array([[ 7, 10],
       [13, 15]])

In [18]:
# some array builtin
arr = np.array([[1,2,4],[3,5,4],[12,4,3]])
arr.sum(axis=0) #sum of all columns
arr.sum(axis=1) #sum of all rows
arr.cumsum(axis=1) #Cumulative sum of each row

array([[ 1,  3,  7],
       [ 3,  8, 12],
       [12, 16, 19]], dtype=int32)

In [19]:
# Universal functions
a = np.arange(3)
b = np.ones(3)
print(np.sqrt(a))
print(np.exp(a))
print(np.add(a,b))

[0.         1.         1.41421356]
[1.         2.71828183 7.3890561 ]
[1. 2. 3.]


In [20]:
a = np.floor(10 * random_instance.random((3,5)))
a.shape
a.ravel() #returns flattented array
a.T #Transposed array

array([[3., 4., 4.],
       [7., 2., 9.],
       [3., 2., 9.],
       [4., 7., 7.],
       [1., 2., 5.]])

## Stacking arrays along different axis

In [21]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,5],[9,3]])
print(np.hstack((a,b))) #Horizontal stacking
print("\n")
print(np.vstack((a,b))) # Vertical stacking

[[ 1  2 11  5]
 [ 3  4  9  3]]


[[ 1  2]
 [ 3  4]
 [11  5]
 [ 9  3]]


In [22]:
np.column_stack((a,b)) #same as hstack but used with two one dimensional array returns two dimensional array
# We have row_stack too...
a = np.array([1,2,3])
b = np.array([4,5,6])
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [23]:
# Newaxis view 1D array as 2D array
a
print(a[:, np.newaxis]) #converts into vertical 2D array i.e 2 dimensional column vector
print("\n\n")
print(a[ np.newaxis, :]) #converts into horizontal 2D array i.e 2 dimensional row vector

[[1]
 [2]
 [3]]



[[1 2 3]]


In [24]:
np.r_[1:7, 10, 6] #create array with ranging elements inside it

array([ 1,  2,  3,  4,  5,  6, 10,  6])

## spliting array into multiple sub arrays

In [25]:
arr = np.arange(0,20)
print("hsplit array ",np.hsplit(arr,5) , "\n") #Splits horizontally into 5 sub-arrays each contains 20/5 =4 elements
print("hsplit array ",np.hsplit(arr, (5,4)) , "\n")
# print(np.vsplit(arr,5)) #Doesnt works on 1D arrays

# Creating 2D array
a = np.arange(20).reshape((4,5))
print(a)
np.vsplit(a,2) 
# np.hsplit(a,4)

hsplit array  [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12, 13, 14, 15]), array([16, 17, 18, 19])] 

hsplit array  [array([0, 1, 2, 3, 4]), array([], dtype=int32), array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [26]:
np.split(arr,4)
np.split(a,4)

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]])]

## Copies and more

In [27]:
# cases whether its copy or not
# case 1 : Not a copy
a = np.arange(10)
b =a 
b is a #B is not a copy of a b represents a its like a pointer to a
b.flags.owndata #This will return true

True

In [28]:
# case 2:not a copy 
def f(x):
    print(id(x)) 

print(id(a))
f(a) #this function doesnt make a copy of given parameter i.e in python function calls makes no copy it passes mutable object as references

2145131591840
2145131591840


In [29]:
# cases : yes makes copy
c = a.view() #this creates new object and shares same data as of a
c is a #will return false
c.flags.owndata #This will also returns false
c.reshape((5,2)) #this will not change shape of a because its copy of that data
a.shape 
c.base is a #returns true because it shares data with a i.e both represents same data 

True

In [30]:
# slicing a array returns its view
a = np.arange(20).reshape((4,5))
print(a)
b = a[:, 1:3]
b[:] = 20
b
a #a changes

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 0, 20, 20,  3,  4],
       [ 5, 20, 20,  8,  9],
       [10, 20, 20, 13, 14],
       [15, 20, 20, 18, 19]])

In [31]:
# Copy makes a complete copy of array with its data
d =a.copy()
d is a
d.base is a
d[0,2] = 50 #doesnt chane value in array 'a'
print(d[0,2])
print(a[0,2])

50
20


In [32]:
a = np.arange(int(1e8)) #this is huge array so copy chould call before slicing if a in not gettting used later that will help in memory usage 
b= a[:100].copy()
b
del a 
# a #error will occur a is not defined

## Advance indexing

In [10]:
arr= np.array([[1,2,3],
              [2,3,5],
              [6,9,8]])
i = np.array([1,2,0,2])
arr[i]

array([[2, 3, 5],
       [6, 9, 8],
       [1, 2, 3],
       [6, 9, 8]])

In [19]:
arr
b =arr >4
print(b)
print("The array sliced using bool array ",arr[b])
arr[b] = 0
arr

[[False False False]
 [False False False]
 [False False False]]
The array sliced using bool array  []


array([[1, 2, 3],
       [2, 3, 0],
       [0, 0, 0]])

## automatic reshaping

In [31]:
a= np.arange(30)
b = a.reshape((2,-1,3))
print(b.shape)
b

(2, 5, 3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

## Vector stacking

In [36]:
a = np.array([1,2,3,4])
b = np.array([1,2,6,4])
np.vstack((a,b))
np.hstack((a,b))
np.column_stack((a,b))

array([[1, 1],
       [2, 2],
       [3, 6],
       [4, 4]])

## More about basic numpy

https://numpy.org/devdocs/user/absolute_beginners.html 


https://numpy.org/devdocs/user/quickstart.html