# Numpy Basic Docs

### Import Package to use

In [1]:
import numpy as np

### Numpy version

In [2]:
np.__version__

'1.19.5'

## Array in numpy

In [3]:
arr = np.array([12,32,4234,4543])
print(arr)
type(arr)

[  12   32 4234 4543]


numpy.ndarray

### n-dimensional array

In [4]:
a = np.array([12,32,24,665], ndmin=4) #4 dimensional array
print(a)
print("Dimension",a.ndim) #.ndim is used to see dimension of array

arr_3 = np.array([[[12,32], [212,54]]])
print("Dimension of arr_3 is ", arr_3.ndim)

[[[[ 12  32  24 665]]]]
Dimension 4
Dimension of arr_3 is  3


## Indexing and slicing of nparray

In [5]:
# Array indexing and slicing is same as in python arrays
print(arr)
print("Indexing")
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print("The sum is :", arr[0] + arr[1])

print("\nSlicing")
print(arr[:])
print(arr[0:2])
print(arr[0:])
print(arr[:4])
print(arr[::-1])
print(arr[::2])

[  12   32 4234 4543]
Indexing
12
32
4234
4543
The sum is : 44

Slicing
[  12   32 4234 4543]
[12 32]
[  12   32 4234 4543]
[  12   32 4234 4543]
[4543 4234   32   12]
[  12 4234]


## More on ndarray

In [6]:
foo = np.array([12,33,54,556,73,29]) #one dimensional array
print("one dimensional array")
print(foo.shape)
print(foo.ndim)
print(foo.size) 
print(type(foo))
print(foo.dtype)
print(foo.dtype.type) #Type of array
print(foo.itemsize) #Data tyooe size of array
print(foo.data)


# Two dimensional array
print("\nTwo dimensional array")
foo2 = np.array([[12,32],[121,322],[123,54]])
print(foo2.shape)
print(foo2.ndim)
print(foo2.size) 
print(type(foo2))
print(foo2.dtype)
print(foo2.dtype.type) #Type of array
print(foo2.itemsize) #Data tyooe size of array
print(foo2.data)

one dimensional array
(6,)
1
6
<class 'numpy.ndarray'>
int32
<class 'numpy.int32'>
4

Two dimensional array
(3, 2)
2
6
<class 'numpy.ndarray'>
int32
<class 'numpy.int32'>
4


## Creation of ndarray

In [7]:
arr = np.array([1,2,3,4,5], dtype=float) #Dtype defines the type of array
arr.dtype #Datatype of an array
arr 

array([1., 2., 3., 4., 5.])

In [8]:
# Zeros array 
arr = np.zeros(5) #Creates array with given shape and initializes elaments with float 0
arr = np.zeros((2,2)) #Two dimensional array
arr = np.zeros((2,2,5)) #Three dimensional arr

# Ones array
arr = np.ones(5) #Creates array with given shape and initializes elaments with float 1
arr = np.ones((2,2)) #Two dimensional array
arr = np.ones((2,2,5)) #Three dimensional arr

# Empty arrays
arr = np.empty(5) #Creates array with given shape and initializes elaments with garbage value
arr = np.empty((2,2)) #Two dimensional array
arr = np.empty((2,2,5)) #Three dimensional arr

# Printing arr
arr

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [9]:
# Arange- creating array  (analogus to range of python)
arr = np.arange(20) #creates array 0 to 20
arr = np.arange(2, 100, 2) #arange(start, stop, step)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [10]:
# Linspace array
arr = np.linspace(1,2,20) #linspace(start , end, how many points between start and end)
arr

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

## Priniting array

In [11]:
arr = np.arange(20).reshape(4,5)
arr
arr>10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## Operations in array

In [12]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([3,4,5,6,7,8,9,])
c=a+b
b = b**2
c>3

array([ True,  True,  True,  True,  True,  True,  True])

In [23]:
random_instance = np.random.default_rng(1)
a = random_instance.random((3,4))
a+=3
a

array([[3.51182162, 3.9504637 , 3.14415961, 3.94864945],
       [3.31183145, 3.42332645, 3.82770259, 3.40919914],
       [3.54959369, 3.02755911, 3.75351311, 3.53814331]])

In [28]:
#matrix operations
a = np.array([[1,2],[4,3]])
b = np.array([[1,0], [3,5]])
a*b #element wise product
a@b  #Matrix product or dot product
a.dot(b)  #Matrix product or dot product

array([[ 7, 10],
       [13, 15]])